### PR TITLE
MCLOUD-5939: Failed deploy with missed env.php

### PR DESCRIPTION
**Pull request by NadiyaS**
### Description

**Steps to reproduce:**
- Install Magento on cloud
- remove app/etc/env.php
- run redeployment

**Actual result**: 
deployment is failed with error:
```
Unhandled error: Notice: Undefined index: db in /app/vendor/magento/ece-too
        W:   ls/src/Step/Deploy/InstallUpdate/ConfigUpdate/DbConnection.php on line 386

```
**Expected Result**: 
deployment finished without errors

### Fixed Issues (if relevant)

1. [Failed deploy with missed env.php](https://jira.corp.magento.com/browse/MCLOUD-5939) 

### Manual testing scenarios

Described in description

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by BarnyShergold** [comment]
There is no description of the issue or how this fix will solve - please add description

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Please add description

**Comment by NadiyaS** [comment]
@BarnyShergold yes. I had to mark it as on hold. Description and tests are added

**Review by shiftedreality — APPROVED** [review]

**Review by BarnyShergold — APPROVED** [review]

**Comment by oshmyheliuk** [comment]
Seems that this solution won't fix a problem as the deploy process will fail later during `setup:upgrade` command.

**Comment by andriyShevtsov** [comment]
Approved. 
But we have another issue in Core so different  error will appear:
```
Running schema recurring...No key available
[2020-05-11 19:12:29] INFO: Set flag: var/.deploy_is_failed
```

**Comment by BaDos** [comment]
This PR can be merged.
Only PostDeployCest is red.
We have the task to fix it https://jira.corp.magento.com/browse/MCLOUD-5968

**Pull request merged**
