### PR TITLE
MAGECLOUD-3806: Error during app:config:import wasn't logged during setup:upgrade

### PR DESCRIPTION
**Pull request by NadiyaS**
https://magento2.atlassian.net/browse/MAGECLOUD-3806

### Description
CLI command setup:upgrade runs app:config:import inside to synchronize scopes data with DB. If scopes data is wrong the command app:config:import itself outputs error message and returns error code, when setup:upgrade command ignores the result of  app:config:import and return success code even when  import was failed.

### Fixed Issues (if relevant)

1. magento/ece-tools#<issue_number>: Issue title

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by mveeramneni** [comment]
Blocked because of core dependency

**Review by shiftedreality — APPROVED** [review]

**Review by billygilbert — APPROVED** [review]

**Comment by andriyShevtsov** [comment]
Patch can't be applied
```[2019-07-16 21:08:55] INFO: Applying patch setup:upgrade failure with app:config:import fail (/app/vendor/magento/ece-tools/patches/MAGECLOUD-3806__failure_setup:upgrade_if_app:config:import_failed__2.3.0.patch) 2.3.0 - 2.3.2.```

**Comment by andriyShevtsov** [comment]
QA approved

**Comment by BaDos** [comment]
I will merge develop branch and then merge this PR.

**Pull request merged**
