### PR TITLE
MAGECLOUD-3874: Remove support if build_options.ini and fail build if it's present

### PR DESCRIPTION
**Pull request by oshmyheliuk**
### Description
Removed support of build_options.ini file. Added critical validator on file existence. 

### Fixed Issues (if relevant)

https://magento2.atlassian.net/browse/MAGECLOUD-3874

### Manual testing scenarios

1. create build_options.ini
2. commit and push changes
3. build fails with an error about unsupported file

### Related PR

https://github.com/magento/devdocs/pull/5198

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by bbatsche — DISMISSED** [review]

**Review by NadiyaS — DISMISSED** [review]

**Review by shiftedreality — DISMISSED** [review]

**Comment by andriyShevtsov** [comment]
QA approved

**Comment by andriyShevtsov** [comment]
@oshmyheliuk  Suggestion from @meker12 Please change text:
- The build_options.ini file is no longer supported.  Modify your configuration to specify build options in the .magento.env.yaml file

**Comment by oshmyheliuk** [comment]
@andriyShevtsov message updated

**Review by NadiyaS — APPROVED** [review]

**Review by bbatsche — APPROVED** [review]

**Comment by andriyShevtsov** [comment]
QA approved

**Pull request merged**
