### PR TITLE
The `guzzlehttp/guzzle` composer dependency has been updated to "^7.3"

### PR DESCRIPTION
**Pull request by andrewbess**
### Description

This pull request (PR) provides update of the `guzzlehttp/guzzle` composer dependency from version `"^6.3"` to version  `"^7.3"`.
**_Reason:_** The `guzzlehttp/guzzle` composer dependency has been updated to version 7.3.0 in "platform-health" project and will be delivered into 2.4-develop next week.
See [this link](https://github.com/magento/magento2/blob/platform-health/composer.json#L38)

### Fixed Issues (if relevant)

1. magento/magento2#32869

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud ECE-tools release notes](https://devdocs.magento.com/cloud/release-notes/ece-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by BarnyShergold** [comment]
@magento run Unit Tests

**Comment by xmav** [comment]
@andrewbess Please use 7.2.5 as minimum PHP version and drop tests configurations for PHP 7.1
CC @andriyShevtsov

**Comment by xmav** [comment]
Closing in favor of #801

**Comment by ghost** [comment]
Hi @andrewbess, thank you for your contribution! </br>Please, complete [Contribution Survey](https://opensource.magento.com/survey/contribution/magento+ece-tools+800), it will take less than a minute. </br>Your feedback will help us to improve contribution process.

**Pull request closed without merging**
