### PR TITLE
MCLOUD-6698: Update deploy ES version config validator

### PR DESCRIPTION
**Pull request by srsathish92**
### Description
https://jira.corp.magento.com/browse/MCLOUD-6698
This PR to update config validator ES version suggestion.

### Fixed Issues (if relevant)

 **Suggesting wrong versions:**
_Ex:_ `- Elasticsearch service version 6.5.4 on infrastructure layer is not compatible with current version of elasticsearch/elasticsearch module (7.8.0.0), used by your Magento application.
    You can fix this issue by upgrading the Elasticsearch service on your Magento Cloud infrastructure to version >=7.4.
  `

### Manual testing scenarios
1. Deploy MC 2.3.5-p2 with ES 6.5
2. Suggestions should be in >=7.5 instead of >=7.4 because ES 7.4 not available in cloud.

### Release notes

Updated the Elasticsearch software compatibility error message suggestions to reflect currently supported versions.

### Associated documentation updates
https://github.com/magento/ece-tools/blob/develop/src/Service/Validator.php#L52
https://github.com/magento/devdocs/pull/7649#discussion_r463753046.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by NadiyaS** [comment]
Hi @srsathish92 ,
please fix unit tests.

**Review by BarnyShergold — APPROVED** [review]

**Review by NadiyaS — APPROVED** [review]

**Review by oshmyheliuk — APPROVED** [review]

**Comment by mveeramneni** [comment]
QA Approved

**Comment by NadiyaS** [comment]
@magento import pr to magento-commerce/ece-tools

**Comment by magento-engcom-team** [comment]
@NadiyaS the pull request successfully imported.

**Pull request merged**
