### PR TITLE
MAGECLOUD-4392: Clean-up ECE-Tools

### PR DESCRIPTION
**Pull request by shiftedreality**
### Fixed Issues (if relevant)

1. https://magento2.atlassian.net/browse/MAGECLOUD-4392

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by YPyltiai** [comment]
@shiftedreality - why do we drop docker parts? Is is something we forgot to move?
Approved removing legacy hooks for `2002.1.0`.

**Review by YPyltiai — APPROVED** [review]
`composer.json` changes approved. Please have developers review the rest.

**Comment by shiftedreality** [comment]
@YPyltiai Docker parts were left as BC to have `docker:build` commands. But having minor release we can just drop that in favor of `magento-cloud-docker` repository

**Comment by YPyltiai** [comment]
> @YPyltiai Docker parts were left as BC to have `docker:build` commands. But having minor release we can just drop that in favor of `magento-cloud-docker` repository

Fine then, that works.

**Review by bbatsche — APPROVED** [review]

**Review by BaDos — APPROVED** [review]

**Comment by shiftedreality** [comment]
No QA needed

**Pull request merged**
