### PR TITLE
MCLOUD-5542: Add mapping for Elastic 7 version validator in ece-tools

### PR DESCRIPTION
**Pull request by shiftedreality**
### Description

ECE-Tools is throwing warnings with both module and service using version 7:

```
Elasticsearch service version 7.2.0 on infrastructure layer is not compatible with current version of elasticsearch/elasticsearch module (6.7.2.0), used by your Magento application.
```

### Fixed Issues (if relevant)

1. https://jira.corp.magento.com/browse/MCLOUD-5542

### Manual testing scenarios

1. Upgrade the ES service to version 7.x
2. Deploy on Magento Cloud
3. See the warning in `var/log/cloud.log`
4. Upgrade the ES module to version 7.x 
5. Deploy on Magento Cloud
6. No warning is present in last deployment

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

releasenotes
Added support for Elasticsearch 7 to deploy validators.

### CODE REVIEW

**Review by BaDos — DISMISSED** [review]

**Comment by BaDos** [comment]
@shiftedreality Do we have some magento-cloud template with ES7 to add test variation to src/Test/Functional/Acceptance/ElasticSearchCest.php ?

**Review by oshmyheliuk — DISMISSED** [review]

**Comment by shiftedreality** [comment]
@BaDos not yet from what I know

**Review by NadiyaS — DISMISSED** [review]

**Review by oshmyheliuk — DISMISSED** [review]

**Comment by andriyShevtsov** [comment]
Proposed changes. Waiting for fix

**Review by BaDos — APPROVED** [review]

**Review by oshmyheliuk — APPROVED** [review]

**Comment by andriyShevtsov** [comment]
Approved

**Pull request merged**
