### PR TITLE
MC-37292: Make 'quality-patches' a hard dependency for ece-tools and soft dependency for magento-cloud-patches

### PR DESCRIPTION
**Pull request by viktym**
### Description
Refactor extensibility approach for magento-cloud-patches & quality-patches to eliminate circular dependency between packages:

- Add magento/quality-patches to 'require'  section of composer.json for magento/ece-tools
- Move magento/quality-patches to 'suggest' section of composer.json for magento/magento-cloud-patches

### Fixed Issues (if relevant)
[MC-37292](https://jira.corp.magento.com/browse/MC-37292): Make 'quality-patches' a hard dependency for ece-tools and soft dependency for magento-cloud-patches

### Related PR
- https://github.com/magento/magento-cloud-patches/pull/75

### Manual testing scenarios
TBD

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud ECE-tools release notes](https://devdocs.magento.com/cloud/release-notes/ece-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by BarnyShergold** [comment]
@magento run all tests

**Review by BarnyShergold — APPROVED** [review]
Approving - can't see why the tests are failing

**Comment by BarnyShergold** [comment]
@magento run all tests

**Comment by BaDos** [comment]
Please see this PR: https://github.com/magento/ece-tools/pull/780

**Pull request closed without merging**
