### PR TITLE
MCLOUD-6658: Enable 2 level cache by default

### PR DESCRIPTION
**Pull request by NadiyaS**
### Description

Since ECE-Tools release 2002.1.1, we can enable L2 cache with variables: https://devdocs.magento.com/cloud/env/variables-deploy.html#redis_backend

### Internal task

1. https://jira.corp.magento.com/browse/MCLOUD-6658

### Manual testing scenarios

- run deployment for Magento version 2.3.5 and higher (without custom cache configurations)
- check that after deployment L2 was enabled by default

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud ECE-tools release notes](https://devdocs.magento.com/cloud/release-notes/ece-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by NadiyaS** [comment]
@magento import pr to magento-cloud/ece-tools

**Comment by magento-engcom-team** [comment]
@NadiyaS the pull request successfully imported.

**Comment by magento-engcom-team** [comment]
@NadiyaS the pull request successfully imported.

**Review by BarnyShergold — APPROVED** [review]

**Review by BarnyShergold — CHANGES_REQUESTED** [review]
Magento\MagentoCloud\Test\Functional\Acceptance\RedisCest::testDefaultConfiguration - definitely needs updating as it is expecting Cm_Cache_Backend_Redis

**Comment by BarnyShergold** [comment]
@NadiyaS - Any news on completing this PR?

**Comment by NadiyaS** [comment]
Hi @BarnyShergold 
We cannot deliver that PR as there are some limitations on integration environments.
I will close this PR for now.

**Pull request closed without merging**
