### PR TITLE
The guzzlehttp/guzzle composer dependency has been updated to "^7.3"

### PR DESCRIPTION
**Pull request by xmav**
### Description
This pull request (PR) provides update of the guzzlehttp/guzzle composer dependency from version "^6.3" to version "^7.3".
Reason: The guzzlehttp/guzzle composer dependency has been updated to version 7.3.0 in "platform-health" project and will be delivered into 2.4-develop next week.
See this link

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/32869

### Release notes

For user-facing changes, add a meaningful release note. For examples, see [Magento Cloud ECE-tools release notes](https://devdocs.magento.com/cloud/release-notes/ece-release-notes.html).

### Associated documentation updates

Add link to Magento DevDocs PR or Issue, if needed.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] Pull request introduces user-facing changes and includes meaningful updates for any required release notes and documentation changes
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by bbatsche — DISMISSED** [review]

**Review by bbatsche — APPROVED** [review]

**Review by michaelcasey316 — APPROVED** [review]

**Comment by bbatsche** [comment]
@magento import pr to https://github.com/magento-commerce/ece-tools

**Comment by m2-github-services** [comment]
@bbatsche an error occurred during the Pull Request import.

**Comment by shiftedreality** [comment]
@magento import pr to magento-commerce/ece-tools

**Comment by m2-github-services** [comment]
@shiftedreality an error occurred during the Pull Request import.

**Pull request merged**
